### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_BLE_Radio#1]
@caternuson tried the example sketches with 2 clues without success?

**Comment by caternuson** [comment]
Here's what I was running. The example in this repo uses a slide switch to set TX vs. RX. Since the CLUE does not have one, I made some dedicated TX and RX programs. They both ran without error, but nothing ever displayed on the RX CLUE.

**On the TX CLUE:**
```python
import time
from adafruit_clue import clue
from adafruit_radio import Radio

r = Radio()

count = 0

while True:
    if clue.button_a or clue.button_b:
        msg = "hello {}".format(count)
        print("Sending a message:", msg)
        r.send(msg)
        count += 1
        time.sleep(0.5)
```

**On the RX CLUE:**
```python
from adafruit_radio import Radio

r = Radio()

while True:
    m = r.receive()
    if m:
        print(m)
```
