### ISSUE TITLE
rename to adafruit_ble_radio?

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_BLE_Radio#3]
I'm thinking maybe we should rename the repo and the library to `adafruit_ble_radio` from `adafruit_radio`, to indicate the transport technology?

**Comment by dhalbert** [comment]
@tannewt Could you comment on this, because if we do rename the library, we should do it sooner rather than later.

**Comment by tannewt** [comment]
I'm game to rename. It'll better future proof it. Want me to?

**Comment by dhalbert** [comment]
Sure, thank you! So repo name, short name, example filenames, and the bundle (if it's in the bundle yet).

**Comment by kattni** [comment]
Done.
